# Generated by Django 3.1.4 on 2021-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=20)),
                ('data', models.CharField(help_text='Данные', max_length=1000000)),
            ],
        ),
    ]
